services:
  playground:
    tty: true
    restart: always
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - playground:/workspace

volumes:
  playground:
